export interface CategoryLayoutItem {
  id: string;
  title: string;
  enabled: boolean;
  viewAllLink: string;
  orderedGameSlugs: string[];
}

export const CASINO_LAYOUT_CATEGORIES: CategoryLayoutItem[] = [
  {
    id: "stake-originals",
    title: "Stake Originals",
    enabled: true,
    viewAllLink: "/casino/group/stake-originals",
    orderedGameSlugs: [
      "mines",
      "crash",
      "plinko",
      "limbo",
      "dice",
      "hilo",
      "keno",
      "wheel",
      "diamonds",
      "roulette",
      "blackjack",
      "baccarat",
      "video-poker",
      "slide",
      "dragon-tower",
      "scarab-spin",
      "blue-samurai",
      "tome-of-life",
    ],
  },
  {
    id: "slots",
    title: "Slots",
    enabled: true,
    viewAllLink: "/casino/group/slots",
    orderedGameSlugs: [
      "sweet-bonanza-1000",
      "gates-of-olympus-1000",
      "sugar-rush-1000",
      "wanted-dead-or-a-wild",
      "chaos-crew-2",
      "rip-city",
      "dork-unit",
      "starlight-princess-1000",
      "san-quentin",
      "tombstone-rip",
      "mental",
      "zeus-vs-hades",
    ],
  },
  {
    id: "live-casino",
    title: "Live Casino",
    enabled: true,
    viewAllLink: "/casino/group/live-casino",
    orderedGameSlugs: [
      "crazy-time",
      "lightning-roulette",
      "xxxtreme-lightning-roulette",
      "speed-auto-roulette",
      "live-blackjack",
      "monopoly-live",
      "mega-ball",
      "hindi-roulette",
      "teen-patti-live",
      "mac88-lightning-dragon-tiger",
      "mac88-lightning-andar-bahar",
      "mac88-3-cards-judgement",
      "roulette-360",
      "ezugi-one-day-teen-patti",
    ],
  },
  {
    id: "game-shows",
    title: "Game Shows",
    enabled: true,
    viewAllLink: "/casino/group/game-shows",
    orderedGameSlugs: [
      "crazy-time",
      "monopoly-live",
      "mega-ball",
      "funky-time",
      "crazy-coin-flip",
      "crazy-pachinko",
      "lightning-dice",
      "balloon-race",
      "red-door-roulette",
      "monopoly-big-baller",
      "stock-market",
    ],
  },
  {
    id: "mac88",
    title: "Mac88 Indian Suite",
    enabled: true,
    viewAllLink: "/casino/group/mac88",
    orderedGameSlugs: [
      "mac88-lightning-dragon-tiger",
      "mac88-lightning-andar-bahar",
      "mac88-dragon-tiger-lion",
      "mac88-dragon-tiger-1-day",
      "mac88-dragon-tiger-2",
      "mac88-lightning-dragon-tiger-2",
      "mac88-29-baccarat",
      "mac88-lightning-baccarat",
      "mac88-sicbo-lightning-sicbo",
      "mac88-roulette",
      "mac88-turbo-auto-roulette",
      "mac88-speed-auto-roulette",
      "mac88-high-low",
      "mac88-dream-wheel",
    ],
  },
  {
    id: "spribe",
    title: "Spribe Arcade",
    enabled: true,
    viewAllLink: "/casino/group/spribe",
    orderedGameSlugs: [
      "aviator",
      "spribe-plinko",
      "spribe-mines",
      "spribe-dice",
      "spribe-goal",
      "spribe-hilo",
      "spribe-hotline",
      "spribe-keno",
      "spribe-balloon",
      "spribe-mini-roulette",
      "spribe-scratch",
      "spribe-fortune-wheel",
      "spribe-blackjack",
      "spribe-russian-poker",
    ],
  },
  {
    id: "smartsoft",
    title: "SmartSoft",
    enabled: true,
    viewAllLink: "/casino/group/smartsoft",
    orderedGameSlugs: [
      "jetx",
      "smartsoft-balloon",
      "plinko-x",
      "cricket-x",
      "helicopter-x",
      "smash-x",
      "double-x",
      "towerx",
      "rollx",
      "cappadocia",
      "smartsoft-lucky-7",
      "smartsoft-roulette",
    ],
  },
  {
    id: "evolution",
    title: "Evolution Gaming",
    enabled: true,
    viewAllLink: "/casino/group/evolution",
    orderedGameSlugs: [
      "crazy-time",
      "lightning-roulette",
      "xxxtreme-lightning-roulette",
      "live-blackjack",
      "monopoly-live",
      "mega-ball",
      "funky-time",
      "crazy-coin-flip",
      "crazy-pachinko",
      "lightning-dice",
      "lightning-baccarat",
      "super-sic-bo",
      "balloon-race",
      "red-door-roulette",
      "bac-bo",
      "football-studio",
      "stock-market",
    ],
  },
  {
    id: "ezugi",
    title: "Ezugi Live",
    enabled: true,
    viewAllLink: "/casino/group/ezugi",
    orderedGameSlugs: [
      "ezugi-andar-bahar",
      "ezugi-teen-patti",
      "ezugi-lucky-7",
      "ezugi-bet-on-teen-patti",
      "ezugi-one-day-teen-patti",
      "ezugi-dragon-tiger",
      "ezugi-cricket-war",
      "ezugi-namaste-roulette",
      "ezugi-speed-baccarat",
      "ezugi-unlimited-blackjack",
      "ezugi-roulette-360",
      "ezugi-auto-roulette",
      "ezugi-ultimate-sic-bo",
    ],
  },
  {
    id: "inout",
    title: "InOut Games",
    enabled: true,
    viewAllLink: "/casino/group/inout",
    orderedGameSlugs: [
      "chicken-road-2",
      "megablock",
      "chicken-road",
      "aviafly",
      "penalty-unlimited",
      "tower-dash",
      "chicken-road-gold",
      "chicken-road-2-bonus",
      "aviafly-2",
      "twist-inout",
      "wheel-out",
      "cricket-road",
      "dragon-pots",
    ],
  },
  {
    id: "100hp",
    title: "100hp Gaming",
    enabled: true,
    viewAllLink: "/casino/group/100hp",
    orderedGameSlugs: [
      "astronaut",
      "airjet",
      "chicken-tour",
      "starx",
      "chicken-vs-train",
      "tappy-bird",
      "astronaut-rivals",
      "hp100-turbo-roulette",
      "hp100-arcade-blackjack",
      "hp100-turbo-dice",
      "hp100-multiplier-blast",
    ],
  },
  {
    id: "jili",
    title: "Jili Games",
    enabled: true,
    viewAllLink: "/casino/group/jili",
    orderedGameSlugs: [
      "jili-mines",
      "gorush",
      "jili-hilo",
      "jili-andar-bahar",
      "jili-tower",
      "jili-limbo",
      "big-small",
      "keno-extra-bet",
      "jili-baccarat",
      "jili-blackjack",
      "jili-roulette",
      "jili-dragon-tiger",
      "super-ace",
      "golden-empire",
      "fortune-gems",
    ],
  },
  {
    id: "evoplay",
    title: "Evoplay Entertainment",
    enabled: true,
    viewAllLink: "/casino/group/evoplay",
    orderedGameSlugs: [
      "thimbles",
      "penalty-shoot-out-street",
      "penalty-shoot-out-super-spin",
      "penalty-shoot-out",
      "hockey-shootout",
      "uncrossable-rush",
      "uncrossable-rush-x-mas",
      "plinko-blast",
      "red-queen",
      "four-aces",
      "more-or-less",
      "french-roulette",
      "european-roulette",
    ],
  },
];

// Alias for backwards compatibility
export const CASINO_LOBBY_CATEGORIES = CASINO_LAYOUT_CATEGORIES;
