import {
  STAKE_ORIGINALS_SLUGS,
  LIVE_CASINO_SLUGS,
  EVOLUTION_SLUGS,
  EZUGI_SLUGS,
  MAC88_SLUGS,
  SPRIBE_SLUGS,
  SMARTSOFT_SLUGS,
  INOUT_SLUGS,
  SLOTS_SLUGS,
  GAME_SHOWS_SLUGS,
  HP100_SLUGS,
  JILI_SLUGS,
  EVOPLAY_SLUGS,
} from "@/data/categories";

export interface CategoryLayoutItem {
  id: string;
  title: string;
  enabled: boolean;
  viewAllLink: string;
  rowBadge?: string;
  showGameTitle?: boolean; // Default: true. Set to false to hide game titles below cards
  showProviderName?: boolean; // Default: true. Set to false to hide provider labels below cards
  orderedGameSlugs: string[];
}

export const CASINO_LAYOUT_CATEGORIES: CategoryLayoutItem[] = [
  {
    id: "stake-originals",
    title: "Stake Originals",
    enabled: true,
    viewAllLink: "/casino/group/stake-originals",
    showGameTitle: false,
    showProviderName: false,
    orderedGameSlugs: STAKE_ORIGINALS_SLUGS,
  },
  {
    id: "live-casino",
    title: "Live Casino",
    enabled: true,
    viewAllLink: "/casino/group/live-casino",
    showGameTitle: false,
    showProviderName: false,
    orderedGameSlugs: LIVE_CASINO_SLUGS,
  },
  {
    id: "inout",
    title: "InOut Games",
    enabled: true,
    viewAllLink: "/casino/group/inout",
    showGameTitle: false,
    showProviderName: false,
    orderedGameSlugs: INOUT_SLUGS,
  },
  {
    id: "publishers",
    title: "Publishers",
    enabled: true,
    viewAllLink: "/casino/collection/providers",
    showGameTitle: true,
    showProviderName: true,
    orderedGameSlugs: [
      "pub-stake",
      "pub-evolution",
      "pub-hacksaw",
      "pub-ezugi",
      "pub-spribe",
      "pub-bgaming",
      "pub-inout",
      "pub-turbogames",
      "pub-smartsoft",
      "pub-pragmatic",
      "pub-nolimit",
      "pub-redtiger",
      "pub-quickspin",
      "pub-thunderkick",
      "pub-elk",
      "pub-yggdrasil",
      "pub-blueprint",
      "pub-btg",
    ],
  },
  {
    id: "evolution",
    title: "Evolution Gaming",
    enabled: true,
    viewAllLink: "/casino/group/evolution",
    showGameTitle: false,
    showProviderName: false,
    orderedGameSlugs: EVOLUTION_SLUGS,
  },
  {
    id: "spribe",
    title: "Spribe",
    enabled: true,
    viewAllLink: "/casino/group/spribe",
    showGameTitle: false,
    showProviderName: false,
    orderedGameSlugs: SPRIBE_SLUGS,
  },
  {
    id: "ezugi",
    title: "Ezugi Live",
    enabled: true,
    viewAllLink: "/casino/group/ezugi",
    showGameTitle: false,
    showProviderName: false,
    orderedGameSlugs: EZUGI_SLUGS,
  },
  {
    id: "game-shows",
    title: "Game Shows",
    enabled: true,
    viewAllLink: "/casino/group/game-shows",
    showGameTitle: false,
    showProviderName: false,
    orderedGameSlugs: GAME_SHOWS_SLUGS,
  },
  {
    id: "smartsoft",
    title: "SmartSoft",
    enabled: true,
    viewAllLink: "/casino/group/smartsoft",
    showGameTitle: false,
    showProviderName: false,
    orderedGameSlugs: SMARTSOFT_SLUGS,
  },
  {
    id: "slots",
    title: "Slots",
    enabled: true,
    viewAllLink: "/casino/group/slots",
    showGameTitle: false,
    showProviderName: false,
    orderedGameSlugs: SLOTS_SLUGS,
  },
  {
    id: "mac88",
    title: "Mac88 Indian Suite",
    enabled: true,
    viewAllLink: "/casino/group/mac88",
    showGameTitle: false,
    showProviderName: false,
    orderedGameSlugs: MAC88_SLUGS,
  },
  {
    id: "100hp",
    title: "100hp Gaming",
    enabled: true,
    viewAllLink: "/casino/group/100hp",
    showGameTitle: false,
    showProviderName: false,
    orderedGameSlugs: HP100_SLUGS,
  },
  {
    id: "jili",
    title: "Jili Games",
    enabled: true,
    viewAllLink: "/casino/group/jili",
    showGameTitle: false,
    showProviderName: false,
    orderedGameSlugs: JILI_SLUGS,
  },
  {
    id: "evoplay",
    title: "Evoplay Entertainment",
    enabled: true,
    viewAllLink: "/casino/group/evoplay",
    showGameTitle: false,
    showProviderName: false,
    orderedGameSlugs: EVOPLAY_SLUGS,
  },
  {
    id: "pragmatic-play",
    title: "Pragmatic Play",
    enabled: true,
    viewAllLink: "/casino/group/pragmatic-play",
    showGameTitle: true,
    showProviderName: true,
    orderedGameSlugs: [
      "gates-of-olympus",
      "sweet-bonanza",
      "sugar-rush",
      "gates-of-olympus-1000",
      "sweet-bonanza-1000",
      "sugar-rush-1000",
      "big-bass-bonanza",
      "wolf-gold",
      "the-dog-house",
      "starlight-princess",
      "fruit-party",
      "madame-destiny-megaways",
      "wild-west-gold",
      "buffalo-king-megaways",
      "great-rhino-megaways",
    ],
  },
  {
    id: "hacksaw-gaming",
    title: "Hacksaw Gaming",
    enabled: true,
    viewAllLink: "/casino/group/hacksaw-gaming",
    showGameTitle: true,
    showProviderName: true,
    orderedGameSlugs: [
      "wanted-dead-or-a-wild",
      "chaos-crew",
      "rip-city",
      "dork-unit",
      "le-bandit",
      "beam-boys",
      "fist-of-destruction",
      "rotten",
      "gladiator-legends",
      "hand-of-anubis",
    ],
  },
  {
    id: "turbogames",
    title: "Turbo Games",
    enabled: true,
    viewAllLink: "/casino/group/turbogames",
    showGameTitle: true,
    showProviderName: true,
    orderedGameSlugs: [
      "turbo-plinko",
      "turbo-mines",
      "turbo-dice-twice",
      "turbo-crash-x",
      "turbo-towers",
      "turbo-hamsta",
      "turbo-double-roll",
      "turbo-hi-lo",
      "turbo-go-roulette",
      "turbo-bubbles",
    ],
  },
  {
    id: "featured-publishers",
    title: "Featured Publishers",
    enabled: true,
    viewAllLink: "/casino/collection/providers",
    showGameTitle: true,
    showProviderName: true,
    orderedGameSlugs: [
      "fpub-evoslot",
      "fpub-no2ap",
      "fpub-ovryx",
      "fpub-titan",
      "fpub-apex",
      "fpub-spinpulse",
      "fpub-volt",
      "fpub-quant",
      "fpub-hyper",
      "fpub-octoplay",
      "fpub-print",
      "fpub-slotmill",
      "fpub-avatarux",
    ],
  },
  {
    id: "only-on-stake",
    title: "Only on Stake",
    enabled: true,
    viewAllLink: "/casino/group/stake-originals",
    rowBadge: "2x VIP",
    showGameTitle: true,
    showProviderName: true,
    orderedGameSlugs: [
      "sharks",
      "wicked-grin",
      "tongue",
      "toon-sailor",
      "dracs-stacks",
      "nuukd",
      "skyscraper-crash",
      "waylanders-forge",
      "odins-vault",
    ],
  },
  {
    id: "burst-games",
    title: "Burst Games",
    enabled: true,
    viewAllLink: "#burst-games",
    showGameTitle: true,
    showProviderName: true,
    orderedGameSlugs: [
      "crash",
      "spaceman",
      "high-flyer",
      "balloon",
      "comet-crash",
      "rocket-dice",
    ],
  },
  {
    id: "new-releases",
    title: "New Releases",
    enabled: true,
    viewAllLink: "#new-releases",
    showGameTitle: true,
    showProviderName: true,
    orderedGameSlugs: [
      "gates-olympus-2500",
      "zombie-academy",
      "dork-show",
      "big-bass-vegas-1000",
      "super-scatter-olympus",
      "blind-viking",
      "hot-chili-chica",
      "moles-gone-wild",
      "rotten",
    ],
  },
];

export const CASINO_LOBBY_CATEGORIES = CASINO_LAYOUT_CATEGORIES;
